# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20161226_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewTitle',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
